Configure handles --version argument itself

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -1,6 +1,6 @@
 #!/bin/bash -x
 ##
-##   BISMON 
+##   BISMON  ---- its Configure script
 ##   Copyright © 2018 - 2021 CEA (Commissariat à l'énergie atomique et aux énergies alternatives)
 ##   contributed by Basile Starynkevitch (working at CEA, LIST, France)
 ##   <basile@starynkevitch.net> or <basile.starynkevitch@cea.fr>
@@ -34,12 +34,30 @@ BISMON_SHORT_GIT="$BISMON_SHGIT1$BISMON_SHGIT2"
 # git repository is dirty, and like 9f60bfd0a2dad6bd if it is clean of
 # local changes.
 
+if [ "$1" == "--version" ]; then
+    printf "%s: version gitid %s\n" $(realpath $0) $BISMON_SHORT_GIT
+    exit 0
+fi
+
 BISMON_CONFIGURE_REAL_PATH=$(realpath $0)
 BISMON_CONFIGURE_DIR=$(dirname $BISMON_CONFIGURE_REAL_PATH)
 $BISMON_CONFIGURE_DIR/timestamp-emit.sh __timestampconf.c
-$CXX -Wall -Wextra -O -g -DBISMON_SHORTGIT=\"$BISMON_SHORT_GIT\" \
+if [ -f BISMON-config ]; then
+    /bin/mv -vf BISMON-config BISMON-config~
+fi
+
+if $CXX -Wall -Wextra -O -g -DBISMON_SHORTGIT=\"$BISMON_SHORT_GIT\" \
      -DBISMON_CONFIG_LABEL=\"from-$BISMON_CONFIGURE_REAL_PATH\" \
-     BISMON-config.cc __timestampconf.c -o BISMON-config -lreadline
-mv __timestampconf.c __timestampconf.c~
+     BISMON-config.cc __timestampconf.c -o BISMON-config -lreadline ; then
+    printf "%s: successfully build %s\n" "$0" $(realpath BISMON-config)
+else
+    printf "%s: failed to build BISMON-config in %s\n" "$0" $(pwd) > /dev/stderr
+    exit 1
+fi
+
+/bin/mv -f __timestampconf.c __timestampconf.c~
+
+exec ./BISMON-config "$@"
+
 
 ### incomplete
