more in Dash-Analyze, but we need to run ./bismon and the GCC compilation commands

diff --git a/Dash-Analyze b/Dash-Analyze
--- a/Dash-Analyze
+++ b/Dash-Analyze
@@ -46,10 +46,17 @@ if [ -f $HOME/.bismon-dash-analyze ]; then
     ##|##    it is running
     ##|##        €.g. BISMON_WEB_BASE=localhost:8087
     ##|##
+    ##|##    BISMON_GCC_PLUGIN is the shared object for our GCC plugin
+    ##|##        €.g  BISMON_GCC_PLUGIN=/tmp/bismon-gcc-plugin.so
+    ##|##
+    ##|##    BISMON_PLUGIN_ASMOUT is used by our
+    ##|##    ./build-gcc10-metaplugin.sh script and could contain some *.s
+    ##|##    file for the assembler file of that plugin.
+    ##|##        €.g  BISMON_PLUGIN_ASMOUT=/tmp/gcc10_metaplugin_BMGCC.s
+    ##|##
     ##|##    BISMONDASH_PROJECT is the name of the Bismon project for
     ##|##    this analysis.
     ##|##        €.g. BISMONDASH_PROJECT=dash_project
-    ##|##
     ##|##
     ##|##    BISMONDASH_PIDFILE is the name of the textual file
     ##|##    containing the pid of Bismon for this analysis.
@@ -90,6 +97,12 @@ if [ -z "$BISMONDASH_PROJECT" ]; then
     export BISMONDASH_PROJECT=dash_bismon_project
 fi
 
+
+## BISMON_GCC_PLUGIN is the shared object for our plugin
+if [ -z "$BISMON_GCC_PLUGIN" ]; then
+    export BISMON_GCC_PLUGIN=$(realpath gccplugins/gcc10_metaplugin_BMGCC.so)
+fi
+
 ## BISMONDASH_PIDFILE is the name of the filepath containing the pid of Bismon
 if [ -z "$BISMONDASH_PIDFILE" ]; then
     export BISMONDASH_PIDFILE=/tmp/bismondash_pidfile
@@ -105,6 +118,8 @@ if [ -f "$BISMONDASH_PIDFILE" ]; then
 	    kill -TERM $bismon_pid
 	fi
     fi
+else
+    pkill --exact --full --signal QUIT bismon || true
 fi
 
 
@@ -133,6 +148,69 @@ if [ -n "$dash_analysis_need_bismon_build" ]; then
     ./Build
 fi
 
+declare -a bismon_dash_args
+
+for f in "$@"; do
+    case "$f" in
+	--bismon*) bismon_dash_args=($bismon_dash_args $f);;
+	--dash-source=*) export BISMONDASH_SOURCE_DASH=$(echo $f | /bin/sed -e s/--msh-source=//);;
+	--asm) export BISMON_PLUGIN_ASMOUT=/tmp/gcc10_metaplugin_BMGCC.s;;
+	--gcc=*) export BISMON_GCC=$(echo $f | /bin/sed -e s/--gcc=//);;
+    esac
+done
+
+
+# https://serverfault.com/a/477506
+if [ ${#bismon_dash_args[@]} -eq 0 ]; then
+    bismon_dash_args=( --bismon-web-base=$BISMON_WEB_BASE --bismon-project-name=$BISMON_DASH_PROJECT --bismon-pid-file=/tmp/_bismon_msh.pid )
+fi
+
+
+echo "$0:" bismon arguments $bismon_msh_args in $(pwd) > /dev/stderr
+
+echo "$0:" msh source $BISMON_MSH_SOURCE > /dev/stderr
+
+
+
+#### check existence of needed files
+
+if [ ! -d gccplugins/ ]; then
+    echo "$0:" missing gccplugins/ directory in $(pwd) > /dev/stderr
+    exit 1
+fi
+
+if [ ! -f gccplugins/gcc10_metaplugin_BMGCC.cc ]; then
+    echo  "$0:" missing gccplugins/gcc10_metaplugin_BMGCC.cc in $(pwd) > /dev/stderr
+    exit 1
+fi
+
+if [ ! -f gccplugins/gcc10_metaplugin_BMGCC.hh ]; then
+    echo  "$0:" missing gccplugins/gcc10_metaplugin_BMGCC.hh in $(pwd) > /dev/stderr
+    exit 1
+fi
+
+if [ ! -x gccplugins/build-gcc10-metaplugin.sh ]; then
+    echo  "$0:" missing or bad gccplugins/build-gcc10-metaplugin.sh script in $(pwd) > /dev/stderr
+    exit 1
+fi
+
+
+### notice that the ./build-gcc10-metaplugin.sh may use the
+### BISMON_PLUGIN_ASMOUT environment variable. For example, set it
+### with export BISMON_PLUGIN_ASMOUT=/tmp/gcc10_metaplugin_BMGCC.s
+
+### on some Debian, there is a bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980609
+pushd gccplugins
+### Notice: the build-gcc10-metaplugin.sh script cares about a BISMON_PLUGIN_ASMOUT shell variable...
+./build-gcc10-metaplugin.sh
+popd
+
+if [ ! -f "$BISMON_GCC_PLUGIN" ]; then
+    printf "%s: missing GCC plugin for Bismon (maybe set %s shell variable)\n" "$0" 'BISMON_GCC_PLUGIN' > /dev/stderr
+    exit 1
+fi
+
+export BISMON_GCC_NAME_PLUGIN=$(basename "$BISMON_GCC_PLUGIN" .so)
 
 printf "%s: incomplete script (pid %s)\n" $0 $$
 exit 1
