the compilation command of Msh-Analuze should use the GCC10 metaplugin

diff --git a/Msh-Analyze b/Msh-Analyze
--- a/Msh-Analyze
+++ b/Msh-Analyze
@@ -37,12 +37,27 @@ if [ -z "$BISMON_GCC" ]; then
     export BISMON_GCC=/usr/bin/gcc-10
 fi
 
-if [ ! -f "$BISMON_MSH_SOURCE/src/builtins.c" \
-       -o ! -f "$BISMON_MSH_SOURCE/src/shellFunctions.c" \
-       -o ! -f "$BISMON_MSH_SOURCE/include/shellFunctions.h" ] ; then
-    printf "%s: invalid MSH source for Bismon %s\n" "$0" "$BISMON_MSH_SOURCE" > /dev/stderr
+if [ ! -d "$BISMON_MSH_SOURCE" ]; then
+    printf "%s: invalid MSH source directory for Bismon %s\n" "$0" "$BISMON_MSH_SOURCE" > /dev/stderr
     exit 1
 fi
+    
+if [ ! -f "$BISMON_MSH_SOURCE/src/builtins.c" ]; then
+    printf "%s: invalid MSH source for Bismon %s without src/builtins.c\n" "$0" "$BISMON_MSH_SOURCE" > /dev/stderr
+    exit 1
+fi
+
+if [ ! -f "$BISMON_MSH_SOURCE/src/shellFunctions.c" ]; then
+    printf "%s: invalid MSH source for Bismon %s without src/shellFunctions.c\n" "$0" "$BISMON_MSH_SOURCE" > /dev/stderr
+    exit 1
+fi
+
+
+if [ ! -f "$BISMON_MSH_SOURCE/include/shellFunctions.h" ]; then
+    printf "%s: invalid MSH source for Bismon %s without include/shellFunctions.h\n" "$0" "$BISMON_MSH_SOURCE" > /dev/stderr
+    exit 1
+fi
+
 
 if [ ! -x bismon ]; then
     ./Build
@@ -116,7 +131,8 @@ sleep 0.3
 
 for src in $BISMON_MSH_SOURCE/src/*.c ; do
     printf "\n\n%s: **** compiling %s ****\n" $0 $src
-    time $BISMON_GCC -Wall -Wextra  -std=gnu11 -g -O -c -c -I $BISMON_MSH_SOURCE/include  $src
+    echo "#§ " $BISMON_GCC -Wall -Wextra  -std=gnu11 -g -O -c -c -I$BISMON_MSH_SOURCE  $src
+    time $BISMON_GCC -Wall -Wextra  -std=gnu11 -g -O -c -c -I$BISMON_MSH_SOURCE  $src
 done
 
 ### missing GCC compilation commands....
